### ISSUE TITLE
Maintenance-Mode not active on the Startpage, although activated in this page.

### ISSUE THREAD

**Issue by lck-git** [TN03/maintenance_xh#1]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=15669&start=60#p73549

**Comment by TN03** [comment]
Redirection of 1st page is working now, but we get the warn message on pages with $s < 0 now.

**Comment by TN03** [comment]
Closed with https://github.com/TN03/maintenance_xh/commit/f7782892ce650d6a9e98e9dec48365e59b6f128f
