### ISSUE TITLE
Maintenance-Mode also for single Onepage websites (?)

### ISSUE THREAD

**Issue by lck-git** [TN03/maintenance_xh#2]
See https://cmsimpleforum.com/viewtopic.php?f=16&t=15669&start=70#p73559

**Comment by TN03** [comment]
I think it's better for onepagers to hide the mintenance pd-tab.

**Comment by lck-git** [comment]
> I think it's better for onepagers to hide the mintenance pd-tab.

### +1

**Comment by TN03** [comment]
Done with: https://github.com/TN03/maintenance_xh/commit/3aaa6a435645bfdd259e1a96788777200492821e
